name: shopify
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  animated_text_kit: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
    - family: KumbhSans
      fonts:
        - asset: fonts/KumbhSans-Regular.ttf
          weight: 500
        - asset: fonts/KumbhSans-Light.ttf
          weight: 100
        - asset: fonts/KumbhSans-Bold.ttf
          weight: 900